CREATE TABLE MEMBER(
    MID NVARCHAR2(20),
    MPW NVARCHAR2(20) NOT NULL,
    MPHONE NVARCHAR2(20),
    MADDR NVARCHAR2(50),
    MGRADE NVARCHAR2(5),
    MNAME NVARCHAR2(10) NOT NULL,
    MSTATE NVARCHAR2(10),
    
    CONSTRAINT PK_MID PRIMARY KEY(MID),
    CONSTRAINT CHECK_MSTATE CHECK(MSTATE IN('가입중', '탈퇴')),
    CONSTRAINT CHECK_MGRADE CHECK(MGRADE IN('D', 'C', 'B', 'A', 'S', '관리자'))
);

ALTER TABLE MEMBER
DROP CONSTRAINT CHECK_MGRADE;

ALTER TABLE MEMBER
ADD CONSTRAINT FK_MGRADE FOREIGN KEY (MGRADE) REFERENCES GRADE(GRADE);

ALTER TABLE MEMBER
MODIFY MGRADE DEFAULT 'D';

ALTER TABLE MEMBER
ADD CONSTRAINT CHECK_MGRADE CHECK(MGRADE IN('D', 'C', 'B', 'A', 'S', '관리자'));

ALTER TABLE MEMBER
DROP CONSTRAINT CHECK_MGRADE;


CREATE TABLE PRODUCT(
    PCODE NUMBER,
    PNAME NVARCHAR2(20) NOT NULL,
    PTYPE NVARCHAR2(10) DEFAULT '기타',
    PPRICE NUMBER CHECK (PPRICE > 0),
    PSTOCK NUMBER CHECK (PSTOCK >= 0),
    
    CONSTRAINT PK_PCODE PRIMARY KEY(PCODE)
);

CREATE TABLE ORDERS(
    OCODE NUMBER,
    OPCODE NUMBER,
    OMID NVARCHAR2(20),
    OCOUNT NUMBER,
    ORDERDATE DATE DEFAULT SYSDATE,
    PURDATE DATE,
    PURWAY NVARCHAR2(10),
    
    CONSTRAINT PK_OCODE PRIMARY KEY(OCODE),
    CONSTRAINT FK_OPCODE FOREIGN KEY(OPCODE) REFERENCES PRODUCT(PCODE),
    CONSTRAINT FK_OMID FOREIGN KEY(OMID) REFERENCES MEMBER(MID),
    CONSTRAINT CHECK_PURWAY CHECK(PURWAY IN ('실시간', '비실시간'))
);

DROP TABLE PRODUCT;

CREATE TABLE GRADE(
    GRADE NVARCHAR2(5),
    PURPRICE NUMBER,
    DISCOUNT NUMBER,
    
    CONSTRAINT PK_GRADE PRIMARY KEY (GRADE),
    CONSTRAINT CHECK_GRADE CHECK(GRADE IN ('A', 'B', 'C', 'D', '관리자'))
);

ALTER TABLE GRADE
DROP CONSTRAINT CHECK_GRADE;

ALTER TABLE GRADE
ADD CONSTRAINT CHECK_GRADE CHECK(GRADE IN ('A', 'B', 'C', 'D', 'GUEST', '관리자'));

ALTER TABLE GRADE
MODIFY GRADE NVARCHAR2(10);

DESC GRADE;

DESC MEMBER;

DESC PRODUCT;

SELECT * FROM MEMBER;

ALTER TABLE PRODUCT ADD PCATEGORY NVARCHAR2(20);

ALTER TABLE PRODUCT MODIFY PTYPE NVARCHAR2(20);

ALTER TABLE PRODUCT DROP COLUMN PPRICE;

ALTER TABLE PRODUCT DROP COLUMN PSTOCK;

ALTER TABLE PRODUCT ADD PPRICE NUMBER;

ALTER TABLE PRODUCT ADD PSTOCK NUMBER;

DESC PRODUCT;

DESC GRADE;

DESC MEMBER;

SELECT * FROM PRODUCT;

INSERT INTO MEMBER(MID, MPW, MGRADE, MNAME )
VALUES('TEST1', '1111', 'A', 'TEST1');

INSERT INTO MEMBER(MID, MPW, MGRADE, MNAME )
VALUES('TEST2', '2222', 'B', 'TEST2');

INSERT INTO MEMBER(MID, MPW, MGRADE, MNAME )
VALUES('TEST3', '3333', 'C', 'TEST3');

INSERT INTO MEMBER(MID, MPW, MGRADE, MNAME )
VALUES('TEST4', '4444', 'D', 'TEST4');

INSERT INTO MEMBER(MID, MPW, MGRADE, MNAME )
VALUES('TESTG', '1111', 'GUEST', 'TESTG');

INSERT INTO MEMBER(MID, MPW, MGRADE, MNAME )
VALUES('TESTA', '1111', '관리자', 'TESTA');

INSERT INTO GRADE
VALUES('A', 200000, 10);

INSERT INTO GRADE
VALUES('B', 150000, 8);

INSERT INTO GRADE
VALUES('C', 100000, 6);

INSERT INTO GRADE
VALUES('D', 50000, 5);

INSERT INTO GRADE
VALUES('GUEST', 0, 0);

INSERT INTO GRADE
VALUES('관리자', 0, 0);

SELECT * FROM MEMBER;

SELECT * FROM MEMBER ORDER BY MGRADE;

select * from grade;

select * from member;

DESC PRODUCT;

DESC ORDERS;

DESC MEMBER;

SELECT NVL(MAX(OCODE),0) + 1 FROM ORDERS;

SELECT * FROM MEMBER;

UPDATE MEMBER
SET MID = 'GUEST', MPW = 'GUEST', MPHONE = 'GUEST', MADDR = 'GUEST', MNAME = 'GUEST', MSTATE = '가입중'
WHERE MGRADE = 'GUEST';

ALTER TABLE ORDERS ADD ORDERSTATE NVARCHAR2(20);

ALTER TABLE ORDERS ADD CONSTRAINT ORDERSTATE CHECK(ORDERSTATE IN('결제필요', '결제완료', '주문확정'));

ALTER TABLE ORDERS MODIFY ORDERSTATE DEFAULT '결제필요';

DESC ORDERS;

COMMIT;


DESC MEMBER;

SELECT * FROM PRODUCT;

select * from member;

DESC GRADE;

SELECT COLUMN_NAME, NULLABLE
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'MEMBER';

SELECT COLUMN_NAME, DATA_TYPE, DATA_DEFAULT
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'MEMBER';

SELECT CONSTRAINT_NAME, COLUMN_NAME
FROM USER_CONS_COLUMNS
WHERE TABLE_NAME = 'MEMBER';

ALTER TABLE MEMBER MODIFY MTOTALPRICE DEFAULT 0;

ALTER TABLE MEMBER ADD CONSTRAINT CHECK_TOTALPRICE CHECK(MTOTALPRICE >= 0);

ALTER TABLE MEMBER MODIFY MSTATE DEFAULT '가입중';


SELECT CONSTRAINT_NAME,
       SEARCH_CONDITION,
       STATUS
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'ORDERS'
  AND CONSTRAINT_TYPE = 'C';


ALTER TABLE MEMBER MODIFY MPHONE NOT NULL;

ALTER TABLE MEMBER MODIFY MADDR NOT NULL;

ALTER TABLE MEMBER MODIFY MSTATE NOT NULL;

SELECT * FROM MEMBER;

DELETE FROM MEMBER WHERE MGRADE IN('관리자');

DESC MEMBER;

DESC GRADE;

INSERT INTO MEMBER
VALUES('ADMIN', 'ADMIN', 'ADMIN', 'ADMIN', '관리자', 'ADMIN', DEFAULT, NULL); 

INSERT INTO MEMBER
VALUES('관리자', '관리자', '관리자', '관리자', '관리자', '관리자', NULL, NULL);

DELETE FROM MEMBER WHERE MID = '관리자';


UPDATE MEMBER SET MID = '관리자' WHERE MID = '관리자';

SELECT * FROM MEMBER;

SELECT * FROM GRADE;

UPDATE GRADE SET PURPRICE = 0 WHERE GRADE = '관리자';

UPDATE GRADE SET DISCOUNT = 3 WHERE GRADE = 'D';

SELECT * FROM GRADE WHERE GRADE NOT IN ('GUEST', '관리자');

UPDATE MEMBER SET MGRADE = 'D' WHERE MID = 'KHC';

SELECT * FROM PRODUCT;

UPDATE PRODUCT SET PSTOCK = 10 WHERE PCODE = 5;

UPDATE PRODUCT SET PSTOCK = 10 WHERE PCODE = 1;

SELECT NVL(MAX(OCODE),0) + 1 FROM ORDERS;

select * from member;

update member set mtotalprice = 0 where mid = 'GUEST';
update member set mtotalprice = 0 where mid = 'ADMIN';

DESC ORDERS;

SELECT * FROM ORDERS;

INSERT INTO ORDERS(OCODE, OPCODE, OMID, OCOUNT, ORDERDATE, PURDATE, PURWAY, ORDERSTATE)
VALUES( 1, 1, 'KHC', 5, DEFAULT, 'NULL', '실시간', '결제필요' );

delete from orders;

SELECT * FROM ORDERS WHERE OMID = 'GUEST' AND ORDERSTATE NOT IN ('주문취소');

SELECT * FROM MEMBER;

SELECT * FROM ORDERS;

UPDATE ORDERS SET PURDATE = SYSDATE;

UPDATE ORDERS SET ORDERSTATE = '결제필요' WHERE ORDERSTATE IN('주문취소');

UPDATE (SELECT * FROM ORDERS WHERE ORDERSTATE IN ('결제필요')) SET ORDERSTATE = '주문취소';

SELECT ORDERDATE, ORDERDATE + 7 FROM ORDERS;

UPDATE ORDERS SET ORDERDATE = SYSDATE - 10;

UPDATE ORDERS SET PURDATE = SYSDATE - 10;

UPDATE ORDERS SET ORDERSTATE = '결제완료';

UPDATE ORDERS SET ORDERSTATE = '주문취소' WHERE SYSDATE >= ORDERDATE + 8 AND ORDERSTATE IN('결제필요');

UPDATE PRODUCT SET PSTOCK = PSTOCK + 3 WHERE PCODE = 33;

UPDATE PRODUCT SET PSTOCK = PSTOCK + 5 WHERE PCODE = 35 OR PCODE = 36;

SELECT * FROM MEMBER;

SELECT * FROM ORDERS;

SELECT * FROM PRODUCT;

SELECT * FROM GRADE WHERE GRADE NOT IN ('GUEST', '관리자');

UPDATE MEMBER SET MGRADE = 'D' WHERE MID = 'KHC';

select * from grade;

SELECT * FROM ORDERS;

SELECT * FROM PRODUCT;

SELECT * FROM MEMBER;

SELECT * FROM MEMBER WHERE MGRADE = 'GUEST';

UPDATE MEMBER SET MGRADE = 'GUEST' WHERE MID = 'GUEST';
