DESC YKD.MEMBER;

INSERT INTO YKD.MEMBER(MID, MPW, MEMAIL, MPHONE, MADDR)
VALUES ( 'KHC', '1234', '202008013@itc.ac.kr', '010-3851-7909', '인천' );

SELECT * FROM YKD.MEMBER;

SELECT * FROM YKD.PRODUCT ORDER BY PCODE;

DESC YKD.PRODUCT;

INSERT INTO YKD.PRODUCT(PCODE, PNAME, PPRICE, PCOMPANY, PTYPE, PSTOCK)
VALUES ( (SELECT NVL(MAX(PCODE),0)+1 FROM YKD.PRODUCT), '세탁기', 1900000, 'LG전자', '가전', 10 );

COMMIT;
