/* SYS 계정 */
/* 공통사용자 규칙 해제 */
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
-- SPRING_KHC 유저 생성
CREATE USER SPRING_KHC IDENTIFIED BY "1234";
-- DBA 권한 부여
GRANT DBA TO SPRING_KHC;

/* SPRING_KHC 계정 */
CREATE TABLE MEMBER(
    MID NVARCHAR2(10),
    MPW NVARCHAR2(10),
    MNAME NVARCHAR2(10),
    MBIRTH DATE
);

ALTER TABLE MEMBER
ADD CONSTRAINT PK_MEMBER PRIMARY KEY(MID);

ALTER TABLE MEMBER
MODIFY MPW NOT NULL;

SELECT * FROM MEMBER;

DROP TABLE MEMBER;

/* MEMBER 컬럼 아이디, 비밀번호, 이름, 가입일, 회원상태(탈퇴 등) */

CREATE TABLE MEMBER(
    MID NVARCHAR2(10),                   -- 아이디(PK)
    MPW NVARCHAR2(10) NOT NULL,          -- 비밀번호(NOT NULL)
    MNAME NVARCHAR2(10),                 -- 이름
    MJOINDATE DATE DEFAULT SYSDATE,      -- 가입일(DEFAULT SYSDATE)
    MSTATE NCHAR(1) DEFAULT 'Y' NOT NULL -- 가입상태(Y,N)
);

ALTER TABLE MEMBER
ADD CONSTRAINTS PK_MID PRIMARY KEY(MID);

ALTER TABLE MEMBER
ADD CONSTRAINTS CHECK_MSTATE CHECK (MSTATE IN('Y', 'N'));

DESC MEMBER;

/* BOARD 컬럼 글번호, 글내용, 업로드 파일(이미지), 조회수 */

CREATE TABLE BOARD(
    BNO NUMBER,                             -- 글번호(PK)
    BWRITER NVARCHAR2(10),                  -- 작성자(FK)
    BTITLE NVARCHAR2(200) NOT NULL,         -- 글제목
    BCONTENTS NVARCHAR2(2000),              -- 글내용
    BHITS NUMBER,                           -- 조회수
    BDATE DATE DEFAULT SYSDATE,             -- 작성일
    BFILENAME NVARCHAR2(2000),              -- 등록 파일명(파일 경로)
    BSTATE NCHAR(1) NOT NULL                -- 상태(Public,Modified,Deleted)
);

ALTER TABLE BOARD
ADD CONSTRAINTS PK_BNO PRIMARY KEY(BNO);

ALTER TABLE BOARD -- BWRITER 컬럼에 MEMBER 테이블의 MID 컬럼을 참조하는 FOREIGN KEY 부여
ADD CONSTRAINTS FK_BWRITER FOREIGN KEY(BWRITER)
REFERENCES MEMBER(MID);

ALTER TABLE BOARD
ADD CONSTRAINTS CHECK_BSTATE CHECK(BSTATE IN('P','M','D'));

ALTER TABLE BOARD
MODIFY BSTATE DEFAULT 'P';

SELECT * FROM BOARD;

DESC BOARD;

INSERT INTO BOARD
VALUES ( 3, 1, 1, 1, 0, DEFAULT, NULL, 'M');

DELETE FROM BOARD;

SELECT * FROM BOARD WHERE BSTATE NOT IN('D') ORDER BY BNO DESC;

SELECT * FROM BOARD;

DELETE FROM BOARD WHERE BNO = 11;

DELETE FROM BOARD;

SELECT * FROM BOARD WHERE BTITLE LIKE '%123%';

/* 댓글 테이블 작성 */
CREATE TABLE REPLY(
    RNO NUMBER,                 -- 댓글 번호(PK)
    RWRITER NVARCHAR2(10),      -- 댓글 작성자( FK-MEMBER(MID) )
    RBNO NUMBER,                -- 원글 번호( FK-BOARD(BNO) )
    RCONTENTS NVARCHAR2(200),   -- 댓글 내용
    RDATE DATE DEFAULT SYSDATE, -- 댓글 작성일
    RSTATE NCHAR(1) DEFAULT 'P' -- 상태('P':공개, 'D':삭제)
);

ALTER TABLE REPLY
ADD CONSTRAINT PK_RNO PRIMARY KEY(RNO);

ALTER TABLE REPLY
ADD CONSTRAINT FK_RWRITER FOREIGN KEY(RWRITER)
    REFERENCES MEMBER(MID);
    
ALTER TABLE REPLY
ADD CONSTRAINT FK_RBNO FOREIGN KEY(RBNO)
    REFERENCES BOARD(BNO);
    
ALTER TABLE REPLY
MODIFY RCONTENTS NOT NULL;

INSERT INTO REPLY
VALUES(1, '1234', 1, '와 정말 유용한 글이었어요', '2025-07-08 15:00:00', DEFAULT );

INSERT INTO REPLY
VALUES(5, '1234', 1, '와 정말요?', DEFAULT, DEFAULT );

INSERT INTO REPLY
VALUES(6, '1234', 1, '저도 같은 생각이에요', DEFAULT, DEFAULT );

INSERT INTO REPLY
VALUES(2, '1234', 3, '테스트', DEFAULT, DEFAULT );

INSERT INTO REPLY
VALUES(3, '1234', 4, '저도 집에 가고싶네요ㅠㅠ', DEFAULT, DEFAULT );

INSERT INTO REPLY
VALUES(4, '1234', 5, '고양이가 귀여워요', DEFAULT, DEFAULT );



SELECT * FROM REPLY WHERE RBNO = 1 AND RSTATE NOT IN ('D') ORDER BY RNO;

SELECT * FROM REPLY WHERE RBNO = 1 ORDER BY RNO;

SELECT * FROM BOARD WHERE BSTATE NOT IN ('D') ORDER BY BNO DESC;

SELECT * FROM BOARD WHERE BSTATE NOT IN ('D') ORDER BY BNO DESC OFFSET 2 ROWS FETCH NEXT 3 ROWS ONLY;

DESC TESTTBL;

DESC TEST_TBL;

SELECT * FROM USER_TABLES;

DESC TEST_TBL01;






























